# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/SSC/Proiect_SSC_ALU/Proiect_SSC_ALU.cache/wt [current_project]
set_property parent.project_path D:/SSC/Proiect_SSC_ALU/Proiect_SSC_ALU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/SSC/Proiect_SSC_ALU/Proiect_SSC_ALU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/SSC/Proiect_SSC_ALU/Proiect_SSC_ALU.srcs/sources_1/new/FullAdder.vhd
  D:/SSC/Proiect_SSC_ALU/Proiect_SSC_ALU.srcs/sources_1/new/Inmultire.vhd
  D:/SSC/Proiect_SSC_ALU/Proiect_SSC_ALU.srcs/sources_1/new/RippleCarrySubtractor.vhd
  D:/SSC/Proiect_SSC_ALU/Proiect_SSC_ALU.srcs/sources_1/new/RippleCarryAdder.vhd
  D:/SSC/Proiect_SSC_ALU/Proiect_SSC_ALU.srcs/sources_1/new/Inmultitor32b.vhd
  D:/SSC/Proiect_SSC_ALU/Proiect_SSC_ALU.srcs/sources_1/new/ControlUnit.vhd
  D:/SSC/Proiect_SSC_ALU/Proiect_SSC_ALU.srcs/sources_1/new/RomMemory.vhd
  D:/SSC/Proiect_SSC_ALU/Proiect_SSC_ALU.srcs/sources_1/new/ALU.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top ALU -part xc7k70tfbv676-1


write_checkpoint -force -noxdef ALU.dcp

catch { report_utilization -file ALU_utilization_synth.rpt -pb ALU_utilization_synth.pb }
